ingressController:
  enabled: true
  env:
    publish_service: kong/kong-dp-kong-proxy
    kong_admin_token: kong_admin_password

image:
  repository: kong/kong-gateway
  tag: "3.7.1.1"

secretVolumes:
  - kong-cluster-cert

env:
  role: control_plane
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key

  database: postgres
  pg_database: kong
  pg_user: kong
  pg_password: demo123
  pg_host: kong-cp-postgresql.kong.svc.cluster.local
  pg_ssl: "off"

  admin_gui_url: http://<EXTERNAL_IP>
  admin_gui_api_url: http://<EXTERNAL_IP>

  admin_gui_session_conf: '{"secret":"secret","storage":"kong","cookie_secure":false}'

  password: kong_admin_password

enterprise:
  enabled: true
  license-secret: kong-enterprise-license

admin:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false

  ingress:
    enabled: true
    hostname: <EXTERNAL_IP>
    path: /
    pathType: Prefix
    ingressClassName: kong

cluster:
  enabled: true
  tls:
    enabled: true

clustertelemetry:
  enabled: true
  tls:
    enabled: true

manager:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false

  ingress:
    enabled: true
    hostname: <EXTERNAL_IP>
    path: /
    pathType: Prefix
    ingressClassName: kong

proxy:
  enabled: false

# ! POSTGRES TESTING-PURPOSE ONLY
# ! DO NOT USE THIS ON PRODUCTION
postgresql:
  enabled: true
  auth:
    password: demo123
