ingressController:
  enabled: false

image:
  repository: kong/kong-gateway
  tag: "3.7.1.1"

secretVolumes:
  - kong-cluster-cert

env:
  role: data_plane
  database: "off"

  cluster_control_plane: kong-cp-kong-cluster.kong.svc.cluster.local:8005
  cluster_telemetry_endpoint: kong-cp-kong-clustertelemetry.kong.svc.cluster.local:8006

  lua_ssl_trusted_certificate: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key

enterprise:
  enabled: true
  license_secret: kong-enterprise-license

proxy:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "kong-hc"}'
  ingress:
    enabled: true
    hostname: proxy.bahanatcw.com
    path: /
    pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: gce

admin:
  enabled: false

manager:
  enabled: false
