ingressController:
  enabled: false

image:
  repository: kong/kong-gateway
  tag: "3.7.1.1"

secretVolumes:
  - kong-cluster-cert

env:
  role: control_plane
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key

  database: postgres
  pg_database: kong
  pg_user: kong
  pg_password: demo123
  pg_host: kong-cp-postgresql.kong.svc.cluster.local
  pg_ssl: "off"

  admin_gui_url: http://manager-kong.bahanatcw.com
  admin_gui_api_url: http://admin-kong.bahanatcw.com
  admin_gui_session_conf: '{"secret":"secret","storage":"kong","cookie_secure":false}'
  admin_gui_auth: basic-auth
  enforce_rbac: "on"

  password: kong_admin_password

enterprise:
  rbac:
    enabled: true
    admin_gui_auth: basic-auth

admin:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "kong-hc"}'
  ingress:
    enabled: true
    hostname: admin-kong.bahanatcw.com
    path: /
    pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: gce

cluster:
  enabled: true
  tls:
    enabled: true

clustertelemetry:
  enabled: true
  tls:
    enabled: true

manager:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false
  annotations:
    beta.cloud.google.com/backend-config: '{"default":"kong-hc"}'
  ingress:
    enabled: true
    hostname: manager-kong.bahanatcw.com
    path: /
    pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: gce

proxy:
  enabled: false

# ! POSTGRES TESTING-PURPOSE ONLY
# ! DO NOT USE THIS ON PRODUCTION
postgresql:
  enabled: true
  auth:
    password: demo123
