apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: kong
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      name: http
    - port: 443
      targetPort: 8443
      name: https
    - port: 8001
      targetPort: 8001
      name: admin
    - port: 8002
      targetPort: 8002
      name: manager
  selector:
    app: kong
